### ISSUE TITLE
你编能开机不

### ISSUE THREAD

**Issue by qiangua2460** [Mayuri-Chan/android_kernel_xiaomi_ruby#1]
我编的不开机

**Comment by wulan17** [comment]
![Uploading IMG_20230512_203300_766.jpg…]()

**Comment by wulan17** [comment]
![IMG_20230512_203300_766](https://github.com/Mayuri-Chan/android_kernel_xiaomi_ruby/assets/18455603/9d6cb214-1d4d-410b-8adf-d64e01bb6752)

**Comment by qiangua2460** [comment]
唉，原来我才是那个小丑！

**Comment by qiangua2460** [comment]
我能在那个社交平台联系到你
